[theme]
base = "dark"
primaryColor = "#34D399"              # green accent
backgroundColor = "#0B1220"           # deep navy (page)
secondaryBackgroundColor = "#111B33"  # cards / panels
textColor = "#E8EEF5"                 # soft white
font = "sans serif"
